let strip = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
let strip2 = neopixel.create(DigitalPin.P1, 5, NeoPixelMode.RGB)
basic.forever(function () {
    strip.clear()
    strip.range(0, input.lightLevel() / 30).showColor(neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    strip2.clear()
    strip2.range(0, Math.abs(input.acceleration(Dimension.X)) / 200).showColor(neopixel.colors(NeoPixelColors.Blue))
    strip2.show()
})
